[package]
name = "drasyl"
version = "0.1.0"
edition = "2021"

[dependencies]
libsodium-sys-stable = { version = "1.22.2", features = ["optimized", "minimal"] }
log = "0.4.25"
env_logger = "0.11.6"
dashmap = "6.1.0"
lazy_static = "1.5.0"