[package]
name = "drasyl"
version = "0.1.0"
edition = "2021"

[dependencies]
libsodium-sys-stable = { version = "1.22.2", features = ["optimized", "minimal"] }
log = "0.4.25"
env_logger = { version = "0.11.6", features = ["humantime", "auto-color"], default-features = false }
dashmap = "6.1.0"
lazy_static = "1.5.0"
ring = "0.17.8"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
debug = false
incremental = false